<?php require_once('Views/Template/header.phtml'); ?>
    <script src="/Js/OpenLayers-2.13.1/OpenLayers.js" type="text/javascript"></script>
    <script src="/Js/qrcodejs/qrcode.js" type="text/javascript"></script>
    <script>
        map = new OpenLayers.Map("map");
        map.addLayer(new OpenLayers.Layer.OSM());

        epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
        projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)

    </script>
<div class="container-fluid home-container">
    <div class="row p-2">
        <div class="col-md-2 col-sm-12">
            <div class="d-flex justify-content-center flex-column align-items-center">
                <h4 class="p-2">Filters</h4>
                <?php require_once('Views/Template/filters.phtml'); ?>
            </div>
        </div>
        <div class="col-md-6">
            <table class="table table-hover">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Deliverer</th>
                    <th>Status</th>
                    <th>Photo</th>
                    <th>Code</th>
                </thead>
                <tbody>
                    <?php /** @var $view */
                    /**
                     * @param $deliveryData
                     * @return void
                     */
                    function deliveryPointTable($deliveryData) //Table function for desktop
                    {
                        $qrcode = "qrcode" . $deliveryData->getId();
                        echo '<script>new QRCode(document.getElementById(qrcode), "http://jindo.dev.naver.com/collie");</script>';
                        echo '<tr><td>' . $deliveryData->getId() . '</td><td>' . $deliveryData->getName() . '</td> <td>' . $deliveryData->getAddressOne() . ' ' . $deliveryData->getAddressTwo() . ' <br>Postcode: ' . $deliveryData->getPostcode() . '<br> Lat/Lng: ' . $deliveryData->getLat() . ', ' . $deliveryData->getLng() . '</td> <td> ' . $deliveryData->getUsername() . '</td> <td>' . $deliveryData->getStatusText() . '</td><td>' . "<img src='Images/" . $deliveryData->getDelPhoto() . "' height='75px' width='75px'>" . '</td> <td><div id="'. $qrcode . '"></div></td></tr>';
                    }

                    if (isset($view->filteredDeliveryDataSet)) { //Records in array looped through to show all stored filtered records
                        foreach ($view->filteredDeliveryDataSet as $deliveryData) {

                            deliveryPointTable($deliveryData);
                        }
                    } elseif (isset($view->deliveryDataSet)) //Records in array to show all records
                        foreach ($view->deliveryDataSet as $deliveryData) {

                            deliveryPointTable($deliveryData);
                        }

                    ?>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div id="map"  style="width:200px;height:200px;">
            </div>
        </div>
    </div>
</div>


<?php require_once('Views/Template/footer.phtml'); ?>