<?php require_once('Views/Template/header.phtml'); ?>



<div class="container-fluid home-container">
    <div class="row py-4">

        <div class="col-md-6">


                <div class="col-md-6">
                    <div class="d-flex justify-content-center flex-column align-items-center">
                        <div class="btn-group dropend">
                            <button type="button" class="btn btn-secondary">
                                Search
                            </button>
                            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="visually-hidden">Toggle Dropright</span>
                            </button>
                            <ul class="dropdown-menu">
                                <!-- Dropdown menu links -->

                            </ul>
                        </div>
                    </div>
                </div>


            <table class="table table-hover">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Deliverer</th>
                    <th>Status</th>
                    <th>Photo</th>
                    <th>Code</th>
                </thead>
                <tbody id="records">
<!--                    --><?php ///** @var $view */
//                    /**
//                     * @param $deliveryData
//                     * @return void
//                     */
//                    function deliveryPointTable($deliveryData) //Table function for desktop
//                    {
//                        $qrcode = "qrcode" . $deliveryData->getId();
//                        echo '<tr><td>' . $deliveryData->getId() . '</td><td>' . $deliveryData->getName() . '</td> <td>' . $deliveryData->getAddressOne() . ' ' . $deliveryData->getAddressTwo() . ' <br>Postcode: ' . $deliveryData->getPostcode() . '<br> Lat/Lng: ' . $deliveryData->getLat() . ', ' . $deliveryData->getLng() . '</td> <td> ' . $deliveryData->getUsername() . '</td> <td>' . $deliveryData->getStatusText() . '</td><td>' . "<img src='Images/" . $deliveryData->getDelPhoto() . "' height='75px' width='75px'>" . '</td> <td><a class="" href="/record.php?id='. $deliveryData->getId() .'" id="'. $qrcode . '"></a></td></tr>';
//                        echo '<script>new QRCode(document.getElementById("'. $qrcode . '"), {text: "/record.php?id='. $deliveryData->getId() .'", width: 75, height: 75});</script>';
//                    }
//
//                    if (isset($view->filteredDeliveryDataSet)) { //Records in array looped through to show all stored filtered records
//                        foreach ($view->filteredDeliveryDataSet as $deliveryData) {
//
//                            deliveryPointTable($deliveryData);
//                        }
//                    } elseif (isset($view->deliveryDataSet)) //Records in array to show all records
//                        foreach ($view->deliveryDataSet as $deliveryData) {
//
//                            deliveryPointTable($deliveryData);
//                        }
//
//                    ?>
                <script>
                    window.addEventListener("load", (event) => {
                        ajaxController.getDeliveries();
                    })
                </script>
                </tbody>
            </table>
        </div>
        <div class="col-md-6 d-flex flex-column justify-content-center align-items-center">
            <div class="" id="map"  style="width: 100%; height: 1000px">

            </div>
        </div>
        <nav aria-label="Page navigation" class="col-md-6">

            <ul class="pagination" id="page-nav">

            </ul>
        </nav>
    </div>
</div>


<?php
//function deliveryPointMarkers($deliveryData) //Table function for desktop
//{
//    echo '<script>
//window.addEventListener("load", (event) => {
//                        createLocation('. $deliveryData->getLat() .','. $deliveryData->getLng() .', "Name: '. $deliveryData->getName() .'" , "'. $deliveryData->getDelPhoto() .'");
//                    })
// </script>';
//}
//foreach ($view->deliveryDataSet as $deliveryData) {
//
//    deliveryPointMarkers($deliveryData);
//}
//?>
<?php require_once('Views/Template/footer.phtml'); ?>