<?php require_once('Views/Template/header.phtml'); ?>



<div class="container-fluid home-container">
    <nav aria-label="Page navigation" class="col-md-6 pt-2">
        <ul class="pagination" id="page-nav">

        </ul>
    </nav>
    <div class="row">
        <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="form-label">Create Record</h4>
                    </div>
                    <div class="modal-body p-4 rounded-2">
                        <div class="mb-3">
                            <label for="recordName" class="form-label">Name</label>
                            <input type="text" class="form-control" id="recordName" name="recordName">
                        </div>
                        <div class="mb-3">
                            <label for="recordAddressOne" class="form-label">Address One</label>
                            <input type="text" class="form-control" id="recordAddressOne" name="recordAddressOne">
                        </div>
                        <div class="mb-3">
                            <label for="recordAddressTwo" class="form-label">Address Two</label>
                            <input type="text" class="form-control" id="recordAddressTwo" name="recordAddressTwo">
                        </div>
                        <div class="mb-3">
                            <label for="recordPostcode" class="form-label">Postcode</label>
                            <input type="text" class="form-control" id="recordPostcode" name="recordPostcode">
                        </div>
                        <div class="mb-3">
                            <label for="recordLat" class="form-label">Lat</label>
                            <input type="text" class="form-control" id="recordLat" name="recordLat">
                        </div>
                        <div class="mb-3">
                            <label for="recordLng" class="form-label">Lng</label>
                            <input type="text" class="form-control" id="recordLng" name="recordLng">
                        </div>
                        <div class="mb-3">
                            <label for="recordDeliverer" class="form-label">Deliverer</label>
                            <select id="recordDeliverer" class="form-select" name='recordDeliverer'>

                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="recordStatus" class="form-label">Status</label>
                            <select class="form-select" id="recordStatus" name="recordStatus">
                            </select>
                        </div>

                        <div class="form-check">
                            <input class="form-check-input" name="confirmCreate" type="checkbox" id="confirmCreate">
                            <label class="form-check-label" for="confirmCreate">
                                Confirm
                            </label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" id="create" value="create" name="createbutton" onclick="ajaxController.createRecord('<?php echo $token ?>')" data-bs-dismiss="modal">Create</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Desktop view -->
        <div class="col-md-6 d-none d-md-block d-lg-block">
            <table class="table table-hover">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Deliverer</th>
                    <th>Status</th>
                    <th>Photo</th>
                    <th>Code</th>
                    <th>Edit</th>
                </thead>
                <tbody id="recordsDesktop">
                <script>
                    window.addEventListener("load", (event) => {
                        ajaxController.getDeliveries(1,'<?php echo $token ?>');
                    })
                </script>
                </tbody>
            </table>
        </div>
        <!--Mobile View -->
        <div class="col-sm-12 d-md-none d-lg-none">
            <table class="table table-hover">
                <thead>
                <th>Details</th>
                <th>Edit</th>
                <th>Photo</th>
                </thead>
                <tbody id="recordsMobile">
                <script>
                    window.addEventListener("load", (event) => {
                        ajaxController.getDeliveries(1,'<?php echo $token ?>', 'mobile');
                    })
                </script>
                </tbody>
            </table>
        </div>


        <!--Desktop view -->
        <div class="col-md-6 d-flex flex-column justify-content-center align-items-center">
            <div class="" id="map"  style="width: 100%; height: 1000px">

            </div>

        </div>
        <!-- Mobile View -->
        <div class="col-sm-12 d-flex flex-column justify-content-center align-items-center">
            <div class="" id="map"  style="width: 100%; height: 50vh">

            </div>

        </div>
    </div>
</div>


    <div class="modal fade" id="recordModal" tabindex="-1" aria-labelledby="recordModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="form-label" id="recordID"></h4>
                </div>
                <div class="modal-body p-4 rounded-2">
                    <div class="mb-3">
                        <label for="recordName" class="form-label">Name</label>
                        <input type="text" class="form-control" id="recordName" name="recordName">
                    </div>
                    <div class="mb-3">
                        <label for="recordAddressOne" class="form-label">Address One</label>
                        <input type="text" class="form-control" id="recordAddressOne" name="recordAddressOne">
                    </div>
                    <div class="mb-3">
                        <label for="recordAddressTwo" class="form-label">Address Two</label>
                        <input type="text" class="form-control" id="recordAddressTwo" name="recordAddressTwo">
                    </div>
                    <div class="mb-3">
                        <label for="recordPostcode" class="form-label">Postcode</label>
                        <input type="text" class="form-control" id="recordPostcode" name="recordPostcode">
                    </div>
                    <div class="mb-3">
                        <label for="recordDeliverer" class="form-label">Deliverer</label>
                        <select id="recordDeliverer" class="form-select" name='recordDeliverer'>

                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="recordStatus" class="form-label">Status</label>
                        <select class="form-select" id="recordStatus" name="recordStatus">
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="recordPhoto" class="form-label">Photo</label>
                        <input type="file" class="form-control" id="recordPhoto" name="recordPhoto">
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" name="confirmEdit" type="checkbox" id="confirmEdit">
                        <label class="form-check-label" for="confirmEdit">
                            Confirm
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" id="edit" value="edit" name="editbutton" onclick="ajaxController.editRecord('<?php echo $token ?>')" data-bs-dismiss="modal">Edit</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Record</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Warning you are about to delete this delivery record</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" id="deleteBtn">Delete</button>
                </div>
            </div>
        </div>
    </div>

<?php require_once('Views/Template/footer.phtml'); ?>