<?php require_once('Views/Template/header.phtml'); ?>
<div class='d-flex my-auto mx-auto p-4 justify-content-center'>

        <div class='d-flex justify-content-center align-items-center mx-auto text-uppercase'>
            <div>
                <h1>Parcel Buddy</h1>
                <h5>The only parcel service you'll need in your life!</h5>
                <br>
                <h6> We pay our workers <em class="fw-lighter">fairly...</em></h6>
                <p class="fw-lighter">And treat your packages with respect (when possible)</p>
            </div>
        </div>
            <img class='img-fluid rounded-3 bg--shadow' src='./Images/parcel_home.webp' alt="hero">
</div>
<?php require_once('Views/Template/footer.phtml'); ?>