<?php require_once('Views/Template/header.phtml'); ?>
<div class='row my-auto mx-auto p-4 align-content-center'>

        <div class='col-md-6 col-sm-12 justify-content-center mx-auto text-uppercase center'>
            <div>
                <h1>Parcel Buddy</h1>
                <h5>The only parcel service you'll need in your life!</h5>
                <br>
                <h6> We pay our workers <em class="fw-lighter">fairly...</em></h6>
                <p class="fw-lighter">And treat your packages with respect (when possible)</p>
            </div>
        </div>
    <div class="col-md-6 col-sm-12">
        <img class='img-fluid rounded-3 bg--shadow' src='./Images/parcel_home.webp' alt="hero">
    </div>

</div>
<?php require_once('Views/Template/footer.phtml'); ?>