<?php require_once('Views/Template/header.phtml'); ?>
<div class='container my-auto mx-auto bg-dark p-4'>
    <div class='row'>
        <div class='d-flex col-md-5 col-sm-1 justify-content-center align-items-center mx-auto'>
            <div>
                <h1>Parcel Buddy</h1>
                <h3>The only parcel service you'll need in your life!</h3>
                <br>
                <h6> We pay our workers <em>fairly...</em></h6>
                <p>And treat your packages with respect (when possible)</p>
            </div>
        </div>
        <div class='col-md-7 col-sm-1'>
            <img class='img-fluid' src='./Images/parcel_home.webp' alt="hero">
        </div>
    </div>

</div>
<?php require_once('Views/Template/footer.phtml'); ?>