<!--<form method="post">-->
<!--    <div class='row p-2'>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="id">-->
<!--                ID-->
<!--            </label>-->
<!--            <div class="col-11">-->
<!--                <input type="number" class="form-control" id="id" name="pointIDInput" placeholder="Search ID"-->
<!--                    aria-label="Recipient's username" aria-describedby="button-addon2">-->
<!--            </div>-->
<!---->
<!--        </div>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="name">-->
<!--                Name-->
<!--            </label>-->
<!--            <div class="col-11">-->
<!--                <input type="text" class="form-control" id="name" name="nameInput" placeholder="Search Name"-->
<!--                    aria-label="Recipient's username" aria-describedby="button-addon2">-->
<!--            </div>-->
<!---->
<!--        </div>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="postcode">-->
<!--                Postcode-->
<!--            </label>-->
<!---->
<!--            <div class="col-11">-->
<!--                <input type="text" class="form-control" id="postcode" name="postcodeInput" placeholder="Search Postcode"-->
<!--                    aria-label="Recipient's username" aria-describedby="button-addon2">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="addressOne">-->
<!--                Address One-->
<!--            </label>-->
<!---->
<!--            <div class="col-11">-->
<!--                <input type="text" class="form-control" id="addressOne" name="addressOneInput"-->
<!--                    placeholder="Search Address One" aria-label="Recipient's username" aria-describedby="button-addon2">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="addressTwo">-->
<!--                Address Two-->
<!--            </label>-->
<!---->
<!--            <div class="col-11">-->
<!--                <input type="text" class="form-control" id="addressTwo" name="addressTwoInput"-->
<!--                    placeholder="Search Address Two" aria-label="Recipient's username" aria-describedby="button-addon2">-->
<!--            </div>-->
<!--        </div>-->
<!--        --><?php //if (strtolower($_SESSION['login']->getUserType()) === 'manager') { ?>
<!---->
<!--            <div class="form-check py-2 col-12">-->
<!--                <label class="form-check-label" for="deliverer">-->
<!--                    Deliverer-->
<!--                </label>-->
<!---->
<!--                <div class="col-11">-->
<!--                    <select id="inputDeliverer" class="form-select" name='delivererInput'>-->
<!--                        <option selected value="">Choose...</option>-->
<!--                        --><?php ///** @var $view */
//                        foreach ($view->userDataSet as $userData) {
//                            echo "<option value='" . $userData->getUserID() . "'>" . $userData->getUsername() . "</option>"; //Fetches all users in the database to assign to delivery
//                        } ?>
<!---->
<!--                    </select>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!---->
<!--        --><?php //} ?>
<!---->
<!---->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="lat">-->
<!--                Lat-->
<!--            </label>-->
<!---->
<!--            <div class="col-11">-->
<!--                <input type="number" class="form-control" id="lat" name="latInput" placeholder="Search Lat"-->
<!--                    aria-label="Recipient's username" step="any" aria-describedby="button-addon2">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="lng">-->
<!--                Lng-->
<!--            </label>-->
<!---->
<!--            <div class="col-11">-->
<!--                <input type="number" class="form-control" name="lngInput" placeholder="Search Lng"-->
<!--                    aria-label="Recipient's username" id="lng" step="any" aria-describedby="button-addon2">-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-check py-2 col-12">-->
<!--            <label class="form-check-label" for="status">-->
<!--                Status-->
<!--            </label>-->
<!---->
<!--            <div class="col-11">-->
<!--                <select id="status" class="form-select" name='statusInput'>-->
<!--                    <option selected value="">Choose...</option>-->
<!--                    --><?php ///** @var $view */
//                    foreach ($view->statusDataSet as $statusData) {
//                        echo "<option value='" . $statusData->getStatusCode() . "'>" . $statusData->getStatusText() . "</option>"; //Fetches all users in the database to assign to delivery
//                    }
//                    ?>
<!--                </select>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="input-group py-2 col-12 d-flex justify-content-evenly">-->
<!--            <button class="col-5 btn mx-1 filter-button" name="filterButton" type="submit"-->
<!--                id="filterButton">Search</button>-->
<!--            <button class="col-5 btn mx-1 clearFilter-button btn-danger" name="clearFilterButton" type="submit"-->
<!--                id="clearFilterButton">Clear</button>-->
<!--        </div>-->
<!--    </div>-->
<!--</form>-->


    <div class="d-flex justify-content-center flex-column align-items-center">
        <div class="btn-group dropbottom"> <!-- use of bootstrap 5 dropdown menu to provide a simple filter menu near the searchbar -->
            <button type="button" class="btn btn-secondary button--filter">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filter" viewBox="0 0 16 16">
                    <path d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5"/>
                </svg>
            </button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split button--filter" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Filters</span>
            </button>
            <ul class="dropdown-menu p-4">
                <!-- Dropdown menu links -->
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="idCheckbox">ID</label>
                        <input type="checkbox" name="idCheckbox" id="idCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="nameCheckbox">Name</label>
                        <input type="checkbox" name="nameCheckbox" id="nameCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="addressOneCheckbox">Address One</label>
                        <input type="checkbox" name="addressOneCheckbox" id="addressOneCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="addressTwoCheckbox">Address Two</label>
                        <input type="checkbox" name="addressTwoCheckbox" id="addressTwoCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="latCheckbox">Lat</label>
                        <input type="checkbox" name="latCheckbox" id="latCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="lngCheckbox">Lng</label>
                        <input type="checkbox" name="lngCheckbox" id="lngCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="postcodeCheckbox">Postcode</label>
                        <input type="checkbox" name="postcodeCheckbox" id="postcodeCheckbox">
                    </div>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="delivererCheckbox">Deliverer</label>
                        <input type="checkbox" name="delivererCheckbox" id="delivererCheckbox" onclick="ajaxController.setDeliverers('<?php echo $token ?>', document.getElementById('delivererFilter'))">
                    </div>
                    <label for="delivererFilter" class="form-label">Deliverer Options</label>
                    <select id="delivererFilter" class="form-select" name='delivererFilter'>

                    </select>
                </li>
                <li class="list-group-item">
                    <div>
                        <label class="form-label" for="statusCheckbox">Status</label>
                        <input type="checkbox" name="statusCheckbox" id="statusCheckbox" onclick="ajaxController.setStatusTypes('<?php echo $token ?>', document.getElementById('statusFilter'))">
                    </div>
                    <label for="statusFilter" class="form-label">Status Options</label>
                    <select id="statusFilter" class="form-select" name='statusFilter'>

                    </select>
                </li>
            </ul>
        </div>
    </div>
