</div>

<footer class="footer navbar-fixed-bottom mt-auto border-2 bg-transparent bg-opacity-10 bg-dark">
    <div class="container-fluid text-white-50 text-center text-muted bg-dark">
        <label class="text-muted">Hello there<i class="px-1 bi bi-emoji-sunglasses-fill"></i></i></label>
    </div>

</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>