</div>

<footer class="footer fixed-bottom mt-auto border-2 bg-transparent bg-opacity-10">
    <div class="container-fluid text-white-50 text-center text-muted">
        <label class="text-muted uppercase">Parcel Buddy &copy; 2024</label>
    </div>

</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="/Js/qrcodejs/qrcode.js" type="text/javascript"></script>
<script src="/Js/ajax.js" type="text/javascript"></script>
<script src="/Js/recordFormData.js" type="text/javascript"></script>
<script src="/Js/OpenLayers-2.13.1/OpenLayers.js" type="text/javascript"></script>
<script src="/Js/map.js" type="text/javascript"></script>
<script>const ajaxController = new AjaxController();</script>
</body>
</html>