<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Reliable delivery service">
    <meta name="author" content="age419">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="Styles/style.css">
    <title>PB -
        <?php /** @var $view */
        echo $view->pageTitle; ?>
    </title> <!-- Displays the page name in the tab using the value stored in pageTitle -->
</head>
<header class="header">
    <?php
    $token = substr(str_shuffle(MD5 (microtime())), 0, 20);
    $_SESSION['ajaxToken'] = $token;
    ?>
    <?php require_once ('navbar.phtml'); ?>
</header>

<body class="px-4 container-fluid vh-100">