<li class="nav-item">
    <button class="btn" data-bs-toggle="dropdown" aria-expanded="false">
        Sign In
    </button>
    <form class="bg-dark p-4 rounded-2 dropdown-menu dropdown-menu-dark" method="post">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary" id="login" value="login" name="loginbutton">Submit</button>
        </div>
        <div class="form-check">
            <input class="form-check-input" name="confirmLogin" type="checkbox" value="" id="confirmBox">
            <label class="form-check-label" for="confirmBox">
                Confirm
            </label>
        </div>


    </form>
</li>