
<!-- use of bootstraps modal to create an easy to use logout menu when the user interacts with the username -->
<button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
    <?php echo ucfirst($_SESSION['login']->getUsername()) ?>
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Logged In as <?php echo $_SESSION['login']->getUsername() ?></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-4 rounded-2">
                <ul class="list-group">
                    <li class="list-group-item">Username: <?php echo ucfirst($_SESSION['login']->getUsername()) ?></li>
                    <li class="list-group-item">Role: <?php echo $_SESSION['login']->getUserType() ?></li>
                </ul>
            </div>
            <form class="modal-footer" method="post">
                <?php if(strtolower($_SESSION['login']->getUserType()) === 'manager') {  ?>
                <?php echo '<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#recordModal" onclick="ajaxController.setUpCreateForm(' . $token .')">Create Record</button>'; }?>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="logout" value="logout" name="logoutbutton">Sign Out</button>
            </form>
        </div>
    </div>
</div>