<form class="input-group align-self-end col-12 w-100">
<!--    <button class="search-button border-0 border-none"><span class="border-0 input-group-text" id="filter-icon"><i-->
<!--                class="bi bi-filter"></i></span></button>-->

<!--    <button class="filter-button border-0 border-none"><span class="border-0 input-group-text" id="search-icon"><i-->
<!--                class="bi bi-search"></i></span></button>-->
    <div class="container" id="suggestions-container">
        <div class="row">

            <input type="text" class="col-12 form-control center search-box" placeholder="Search Delivery..." aria-label="Search" aria-describedby="search"
                   onkeyup="getSearch(this.value)">
            <ul class="col-12 position-absolute list-group center suggestions" id="suggestions">
            </ul>
        </div>
    </div>
</form>