
<div class="d-flex input-group">
                <span><?php require_once ('filters.phtml'); ?></span>
<input type="search" class="form-control search--input" placeholder="Search..." aria-label="Search" onkeyup="ajaxController.getSearch(this.value, 1 ,'<?php echo $token ?>')">
<span><button class="button button--tertiary button--search"><svg xmlns="http://www.w3.org/2000/svg"
                                                                  width="16" height="16" fill="currentColor" class="bi bi-search search--icon"
                                                                  viewBox="0 0 16 16">
                            <path
                                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                        </svg></button></span> <!-- Use of svg to give a search icon to the search button -->
</div>